# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_caption.proto
# Protobuf Python Version: 5.27.0-rc2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '-rc2',
    'image_caption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image_caption.proto\"r\n\x0e\x43\x61ptionRequest\x12\x11\n\timage_url\x18\x01 \x01(\t\x12\x16\n\x0emax_new_tokens\x18\x02 \x01(\x05\x12\x13\n\x0btemperature\x18\x03 \x01(\x02\x12\x11\n\tuse_cache\x18\x04 \x01(\x08\x12\r\n\x05top_k\x18\x05 \x01(\x05\"\"\n\x0f\x43\x61ptionResponse\x12\x0f\n\x07\x63\x61ption\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_caption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPTIONREQUEST']._serialized_start=23
  _globals['_CAPTIONREQUEST']._serialized_end=137
  _globals['_CAPTIONRESPONSE']._serialized_start=139
  _globals['_CAPTIONRESPONSE']._serialized_end=173
# @@protoc_insertion_point(module_scope)
